# (query: "(chat.openai.com/share OR g.co/gemini/share) in:file,commits,body is:pr is:merged",
#                     type: ISSUE,
#                     first: 20,
#                     {after})

def query_composer(cursor=None, p_cursor=None):
    # (chat.openai.com/share OR g.co/gemini/share OR gemini.google.com/share OR chat.openai.com/g/ OR api.anthropic.com OR api.mistral.ai OR api.deepseek.com OR huggingface.co/spaces/ OR poe.com OR api.perplexity.ai OR deepseek-ai OR bardapi OR OPENAI_API_KEY OR prompt engineering OR LlamaForCausalLM OR deepseek-coder OR deepseek-llm OR huggingface.co/deepseek-ai OR generativelanguage.googleapis.com OR huggingface.co/meta-llama OR huggingface.co/mistralai OR huggingface.co/anthropic OR huggingface.co/deepseek-ai) in:file,commits,body is:pr is:merged
    # (chat.openai.com/share OR g.co/gemini/share OR gemini.google.com/share OR chat.openai.com/g/ OR huggingface.co/spaces/ OR poe.com OR deepseek-ai OR deepseek-coder OR deepseek-llm OR bardapi OR prompt engineering OR LlamaForCausalLM OR powered by ChatGPT OR generated by Claude OR built with Gemini OR AI-generated content OR uses large language model OR using DeepSeek OR with DeepSeek Coder OR huggingface.co/meta-llama OR huggingface.co/mistralai OR huggingface.co/anthropic OR huggingface.co/deepseek-ai) in:file,commits,body is:pr is:merged
    # Atualmente: (chat.openai.com/share OR g.co/gemini/share) in:file,commits,body is:pr is:merged

    cursor_part = f', after: "{cursor}"' if cursor else ""
    page_cursor = f', after: "{p_cursor}"' if p_cursor else ""
    query = f"""query {{
                  search(query: "(huggingface.co/anthropic) in:file,commits,body is:pr is:merged",
                    type: ISSUE,
                    first: 10{cursor_part}) {{
                        pageInfo {{
                            endCursor
                            hasNextPage
                        }}
                        issueCount
                        edges {{
                            node {{
                                ... on PullRequest {{                                    
                                    url
                                    title
                                    createdAt
                                    mergedAt
                                    state   
                                    repository {{
                                        stargazerCount
                                        isFork
                                        primaryLanguage {{
                                            name
                                        }}
                                    }}
                                    files (first: 10{page_cursor}) {{
                                        pageInfo {{
                                            endCursor
                                            hasNextPage
                                        }}
                                        edges {{
                                            node {{
                                                path
                                            }}
                                        }}
                                    }}
                                }}
                            }}
                        }}
                    }}
                }}"""
    return query


def searchLLMQuery(cursor=None):
    after = f'after: "{cursor}"' if cursor else ''
    
    query = f"""query {{
                  search(query: "(chat.openai.com/share OR g.co/gemini/share) in:file,commits,body is:pr is:merged",
                    type: ISSUE,
                    first: 20,
                    {after}) {{ 
                        pageInfo {{
                            endCursor
                            hasNextPage
                        }}
                        issueCount
                        edges {{
                            node {{
                                ... on PullRequest {{                                    
                                    url
                                    title
                                    createdAt
                                    mergedAt
                                    state   
                                    repository {{
                                        stargazerCount
                                        isFork
                                        primaryLanguage {{
                                            name
                                        }}
                                    }}
                                    files (first: 100) {{
                                        edges {{
                                            node {{
                                                path
                                            }}
                                        }}
                                    }}
                                }}
                            }}
                        }}
                    }}
                }}"""
    return query

def chatgptQuery():
    query = f"""query {{
                  search(query: "chat.openai.com/share in:file,commits,body is:pr is:merged",
                    type: ISSUE,
                    first: 10) {{ 
                        pageInfo {{
                            endCursor
                            hasNextPage
                        }}
                        issueCount
                        edges {{
                            node {{
                                ... on PullRequest {{                                    
                                    url
                                    title
                                    createdAt
                                    mergedAt
                                    state   
                                    repository {{
                                        stargazerCount
                                        isFork
                                        primaryLanguage {{
                                            name
                                        }}
                                    }}
                                    files (first: 100) {{
                                        edges {{
                                            node {{
                                                path
                                            }}
                                        }}
                                    }}
                                }}
                            }}
                        }}
                    }}
                }}"""
    return query


def geminiQuery():
    query = f"""query {{
                  search(query: "g.co/gemini/share in:file,commits,body is:pr is:merged",
                    type: ISSUE,
                    first: 100) {{
                        pageInfo {{
                            endCursor
                            hasNextPage
                        }}
                        issueCount
                        edges {{
                            node {{
                                ... on PullRequest {{                                    
                                    url
                                    title
                                    createdAt
                                    mergedAt
                                    state   
                                    repository {{
                                        stargazerCount
                                        isFork
                                        primaryLanguage {{
                                            name
                                        }}
                                    }}
                                    files (first: 100) {{
                                        edges {{
                                            node {{
                                                path
                                            }}
                                        }}
                                    }}
                                }}
                            }}
                        }}
                    }}
                }}"""
    return query
